services:
    container_name: postgres
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=popcorn-palace
      - POSTGRES_PASSWORD=popcorn-palace
      - POSTGRES_DB=popcorn-palace
    ports:
      - 5432:5432



